BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "USERS" (
	"USER ID"	INTEGER NOT NULL,
	"NAME"	TEXT NOT NULL,
	"EMAIL ADDRESS"	VARCHAR(255) NOT NULL,
	"AGE"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "DELIVERIES" (
	"DELIVERY ID"	INTEGER NOT NULL,
	"DATE OF DELIVERY"	DATE NOT NULL,
	"USER ID"	INTEGER NOT NULL,
	"PRODUCT ID"	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS "PRODUCTS" (
	"PRODUCT ID"	INTEGER NOT NULL,
	"PRODUCT NAME"	TEXT NOT NULL,
	"MODEL"	VARCHAR(255) NOT NULL,
	"PRICE"	NUMERIC NOT NULL,
	PRIMARY KEY("PRODUCT ID")
);
COMMIT;
